<?php

namespace Modules\Manufacturing\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use App\Models\DeliveryNote;
use App\Models\Material;
use App\Models\Supplier;
use App\Models\Warehouse;
use App\Models\User;
use App\Models\MaterialMovement;
use App\Services\NotificationService;
use App\Traits\StoresNotifications;
use Modules\Manufacturing\Traits\LogsOperations;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class DeliveryNoteController extends Controller
{
    use LogsOperations, StoresNotifications;

    protected $notificationService;

    public function __construct(NotificationService $notificationService)
    {
        $this->notificationService = $notificationService;
    }

    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $query = DeliveryNote::with(['material', 'receiver', 'supplier', 'destination']);

        // فلتر حسب النوع (واردة/صادرة)
        if ($request->filled('type')) {
            $query->where('type', $request->type);
        }

        // فلتر حسب الحالة
        if ($request->filled('status')) {
            $query->where('status', $request->status);
        }

        // فلتر حسب رقم الأذن
        if ($request->filled('delivery_number')) {
            $query->where('note_number', 'like', '%' . $request->delivery_number . '%');
        }

        // بحث عام
        if ($request->filled('search')) {
            $query->where(function($q) use ($request) {
                $q->where('note_number', 'like', '%' . $request->search . '%')
                  ->orWhere('notes', 'like', '%' . $request->search . '%')
                  ->orWhere('driver_name', 'like', '%' . $request->search . '%');
            });
        }

        // ترتيب البيانات حسب الأحدث أولاً مع الباجنيشن
        $deliveryNotes = $query->orderBy('created_at', 'desc')
            ->paginate(15)
            ->appends($request->query());

        return view('manufacturing::warehouses.delivery-notes.index', compact('deliveryNotes'));
    }

    /**
     * Show the form for creating a new resource.
     * ✅ تم التعديل: إضافة قائمة المستودعات
     */
    public function create()
    {
        // ✅ استخدام المنتجات الموجودة في المستودع (اختياري الآن)
        $materialDetails = \App\Models\MaterialDetail::with(['material', 'warehouse', 'unit'])
            ->where('quantity', '>', 0)
            ->get();

        // Debug: Log the material details to see what we're getting
        \Illuminate\Support\Facades\Log::info('Material Details Count: ' . $materialDetails->count());
        \Illuminate\Support\Facades\Log::info('First Material Detail: ' . $materialDetails->first());

        $suppliers = Supplier::all();
        $warehouses = Warehouse::all(); // ✅ قائمة المستودعات
        $users = User::all();

        // توليد رقم الأذن تلقائياً
        $autoGeneratedNumber = $this->generateDeliveryNoteNumber();

        return view('manufacturing::warehouses.delivery-notes.create', compact(
            'materialDetails',
            'suppliers',
            'warehouses', // ✅ تمرير المستودعات
            'users',
            'autoGeneratedNumber'
        ));
    }

    /**
     * Generate a unique delivery note number
     */
    private function generateDeliveryNoteNumber()
    {
        $prefix = 'DN-' . date('Y') . '-';
        $lastNote = DeliveryNote::where('note_number', 'like', $prefix . '%')
            ->orderBy('note_number', 'desc')
            ->first();

        if ($lastNote) {
            // Extract the number from the last note
            $lastNumber = (int) substr($lastNote->note_number, strlen($prefix));
            $newNumber = $lastNumber + 1;
        } else {
            $newNumber = 1;
        }

        return $prefix . str_pad($newNumber, 4, '0', STR_PAD_LEFT);
    }

    /**
     * Store a newly created resource in storage.
     * ✅ تم التعديل: يسمح بتسجيل الأذن بدون مادة محددة (اختيار المستودع فقط)
     */
    public function store(Request $request)
    {
        try {
            // التحقق من البيانات بناءً على النوع
            $type = $request->input('type', 'incoming');

            // إذا كان الرقم فارغاً، توليد رقم جديد
            $deliveryNumber = $request->input('delivery_number');
            if (empty($deliveryNumber)) {
                $deliveryNumber = $this->generateDeliveryNoteNumber();
            }

            // ✅ المرحلة 1: بيانات أساسية فقط - الأوزان والكميات ستُضاف في التسجيل
            $validated = $request->validate([
                'type' => 'required|in:incoming,outgoing',
                'delivery_date' => 'required|date',
                'material_id' => $type === 'outgoing' ? 'required|exists:materials,id' : 'nullable|exists:materials,id',
                'material_detail_id' => $type === 'outgoing' ? 'required|exists:material_details,id' : 'nullable|exists:material_details,id',
                'warehouse_id' => $type === 'incoming' ? 'required|exists:warehouses,id' : 'nullable',
                'warehouse_from_id' => $type === 'outgoing' ? 'required|exists:warehouses,id' : 'nullable|exists:warehouses,id',
                'delivery_quantity' => $type === 'outgoing' ? 'required|numeric|min:0.01' : 'nullable|numeric|min:0',
                'actual_weight' => 'nullable|numeric|min:0', // ✅ اختياري - سيتم تعبئته في التسجيل
                'weight_from_scale' => 'nullable|numeric|min:0', // ✅ اختياري - سيتم تعبئته في التسجيل
                'invoice_weight' => 'nullable|numeric|min:0',
                'driver_name' => 'nullable|string|max:255',
                'vehicle_number' => 'nullable|string|max:50',
                'received_by' => 'nullable|exists:users,id',
                'supplier_id' => $type === 'incoming' ? 'required|exists:suppliers,id' : 'nullable',
                'destination_id' => $type === 'outgoing' ? 'required|string' : 'nullable', // ✅ تغيير: قبول أي قيمة نصية
                'invoice_number' => 'nullable|string|max:100',
                'invoice_reference_number' => 'nullable|string|max:100',

            ], [
                // رسائل الخطأ بالعربي
                'type.required' => 'نوع الأذن مطلوب',
                'type.in' => 'نوع الأذن غير صحيح',
                'delivery_date.required' => 'التاريخ مطلوب',
                'delivery_date.date' => 'التاريخ غير صحيح',
                'warehouse_id.required' => 'المستودع مطلوب',
                'warehouse_id.exists' => 'المستودع المختار غير موجود',
                'material_id.required' => 'يجب اختيار المادة للأذن الصادرة',
                'material_id.exists' => 'المادة المختارة غير موجودة',
                'material_detail_id.required' => 'يجب اختيار المستودع المصدر',
                'material_detail_id.exists' => 'المستودع المصدر غير موجود',
                'warehouse_from_id.required' => 'يجب اختيار المستودع المصدر للأذن الصادرة',
                'warehouse_from_id.exists' => 'المستودع المصدر غير موجود',
                'delivery_quantity.required' => 'الكمية مطلوبة للأذن الصادرة',
                'delivery_quantity.numeric' => 'الكمية يجب أن تكون رقماً',
                'delivery_quantity.min' => 'الكمية يجب أن تكون أكبر من صفر',
                'actual_weight.numeric' => 'الوزن يجب أن يكون رقماً',
                'actual_weight.min' => 'الوزن لا يمكن أن يكون سالباً',
                'weight_from_scale.numeric' => 'وزن الميزان يجب أن يكون رقماً',
                'weight_from_scale.min' => 'وزن الميزان لا يمكن أن يكون سالباً',
                'invoice_weight.numeric' => 'وزن الفاتورة يجب أن يكون رقماً',
                'driver_name.string' => 'اسم السائق يجب أن يكون نصاً',
                'driver_name.max' => 'اسم السائق طويل جداً',
                'vehicle_number.string' => 'رقم المركبة يجب أن يكون نصاً',
                'vehicle_number.max' => 'رقم المركبة طويل جداً',
                'received_by.exists' => 'المستخدم المختار غير موجود',
                'supplier_id.required' => 'المورد مطلوب للأذن الواردة',
                'supplier_id.exists' => 'المورد المختار غير موجود',
                'destination_id.required' => 'الوجهة مطلوبة للأذن الصادرة',
                'destination_id.string' => 'الوجهة يجب أن تكون نصاً',
                'invoice_number.string' => 'رقم الفاتورة يجب أن يكون نصاً',
                'invoice_reference_number.string' => 'رقم مرجع الفاتورة يجب أن يكون نصاً',
                'notes.string' => 'الملاحظات يجب أن تكون نصاً',
            ]);

            // Prepare the data
            $validated['note_number'] = $deliveryNumber;

            // ✅ للإذن الصادر: استخدام المستودع المصدر كـ warehouse_id
            if ($type === 'outgoing' && !empty($validated['warehouse_from_id'])) {
                $validated['warehouse_id'] = $validated['warehouse_from_id'];
            }

            // ✅ إذا كان هناك وزن فعلي، استخدمه كـ delivered_weight
            if (!empty($validated['actual_weight'])) {
                $validated['delivered_weight'] = $validated['actual_weight'];
            }

            // ✅ إذا كان هناك material_detail_id، استخدم بيانات المادة
            if (!empty($validated['material_detail_id'])) {
                $materialDetail = \App\Models\MaterialDetail::findOrFail($validated['material_detail_id']);
                if (empty($validated['material_id'])) {
                    $validated['material_id'] = $materialDetail->material_id;
                }
            }

            // ✅ للإذن الوارد: إذا لم يكن هناك material_id، اجعله null (سيتم تحديده لاحقاً في التسجيل)
            if ($type === 'incoming' && empty($validated['material_id'])) {
                $validated['material_id'] = null;
            }

            // ✅ للإذن الصادر: التأكد من أن material_id موجود
            if ($type === 'outgoing' && empty($validated['material_id'])) {
                throw new \Exception('يجب تحديد المادة للأذن الصادرة');
            }

            // Set the user fields
            $validated['received_by'] = $validated['received_by'] ?? Auth::id() ?? 1;
            $validated['recorded_by'] = Auth::id() ?? 1;

            // Calculate weight discrepancy if both weights exist
            if (!empty($validated['actual_weight']) && !empty($validated['invoice_weight'])) {
                $validated['weight_discrepancy'] = $validated['actual_weight'] - $validated['invoice_weight'];
            }

            DB::beginTransaction();

            // Create the delivery note
            $deliveryNote = DeliveryNote::create($validated);

            // ✅ تسجيل الحركة في material_movements
            // ملاحظة: للأذن الوارد في المرحلة 1، لا نسجل حركة لأنه لا توجد مادة بعد
            // سيتم تسجيل الحركة لاحقاً عند التسجيل (المرحلة 2)
            if ($type === 'outgoing' && !empty($validated['delivery_quantity']) && $validated['delivery_quantity'] > 0) {
                $materialDetail = null;
                if (!empty($validated['material_detail_id'])) {
                    $materialDetail = \App\Models\MaterialDetail::find($validated['material_detail_id']);
                }

                MaterialMovement::create([
                    'movement_number' => MaterialMovement::generateMovementNumber(),
                    'movement_type' => 'outgoing',
                    'source' => 'registration',
                    'delivery_note_id' => $deliveryNote->id,
                    'material_detail_id' => $validated['material_detail_id'] ?? null,
                    'material_id' => $validated['material_id'],
                    'unit_id' => $materialDetail ? $materialDetail->unit_id : null,
                    'quantity' => $validated['delivery_quantity'],
                    'from_warehouse_id' => $validated['warehouse_id'],
                    'to_warehouse_id' => null,
                    'supplier_id' => null,
                    'destination' => $validated['destination_id'] ?? 'غير محدد',
                    'description' => 'خروج بضاعة - أذن رقم ' . $deliveryNumber,
                    'notes' => $validated['notes'] ?? null,
                    'reference_number' => $validated['invoice_number'] ?? null,
                    'created_by' => Auth::id() ?? 1,
                    'movement_date' => now(),
                    'ip_address' => $request->ip(),
                    'user_agent' => $request->userAgent(),
                    'status' => 'completed',
                ]);
            }            // ✅ تحديث كمية المستودع (للصادر فقط في المرحلة 1)
            if ($type === 'outgoing' && !empty($validated['material_detail_id']) && !empty($validated['delivery_quantity'])) {
                try {
                    $materialDetail = \App\Models\MaterialDetail::find($validated['material_detail_id']);
                    // أذن صادرة - تقليل الكمية
                    if ($materialDetail->quantity < $validated['delivery_quantity']) {
                        throw new \Exception('الكمية المتوفرة غير كافية');
                    }
                    $materialDetail->quantity -= $validated['delivery_quantity'];
                    $materialDetail->save();
                } catch (\Exception $inventoryError) {
                    Log::error('Failed to update inventory: ' . $inventoryError->getMessage());
                    // حذف أذن التسليم إذا فشل تحديث المستودع
                    $deliveryNote->delete();
                    throw new \Exception('فشل تحديث المستودع: ' . $inventoryError->getMessage());
                }
            }

            // Log the operation
            try {
                $this->logOperation(
                    'create',
                    'Create Delivery Note',
                    'تم إنشاء أذن تسليم ' . ($type === 'incoming' ? 'واردة' : 'صادرة') . ' جديدة: ' . $deliveryNote->note_number,
                    'delivery_notes',
                    $deliveryNote->id,
                    null,
                    $deliveryNote->toArray()
                );
            } catch (\Exception $logError) {
                Log::error('Failed to log delivery note creation: ' . $logError->getMessage());
                // Don't throw - just log the error, operation already completed
            }

            // إرسال الإشعارات
            try {
                $managers = User::where('role', 'admin')->orWhere('role', 'manager')->get();
                foreach ($managers as $manager) {
                    $this->notificationService->notifyDeliveryNoteRegistered(
                        $manager,
                        $deliveryNote,
                        Auth::user()
                    );
                }

                // ✅ تخزين الإشعار في قاعدة البيانات
                $type = $request->input('type', 'incoming');
                $this->storeNotification(
                    'delivery_note_created',
                    'أذن تسليم ' . ($type === 'incoming' ? 'واردة' : 'صادرة') . ' جديدة',
                    'تم إنشاء أذن تسليم جديدة برقم: ' . $deliveryNote->note_number,
                    $type === 'incoming' ? 'success' : 'info',
                    $type === 'incoming' ? 'fas fa-arrow-down' : 'fas fa-arrow-up',
                    route('manufacturing.delivery-notes.show', $deliveryNote->id)
                );
            } catch (\Exception $notifError) {
                Log::warning('Failed to send delivery note notifications: ' . $notifError->getMessage());
            }

            DB::commit();

            $successMessage = $type === 'incoming'
                ? 'تم إضافة أذن التسليم الواردة بنجاح - رقم الأذن: ' . $deliveryNumber
                : 'تم إضافة أذن التسليم الصادرة بنجاح - رقم الأذن: ' . $deliveryNumber . ' ✅ تم تسجيلها في سجل العمليات';

            // For incoming delivery notes, redirect to registration page
            if ($type === 'incoming') {
                return redirect()->route('manufacturing.warehouse.registration.create', $deliveryNote)
                    ->with('success', $successMessage);
            }

            return redirect()->route('manufacturing.delivery-notes.index')
                ->with('success', $successMessage);
        } catch (\Exception $e) {
            DB::rollBack();
            Log::error('Error creating delivery note: ' . $e->getMessage(), [
                'exception' => $e,
                'input' => $request->all()
            ]);
            return redirect()->back()
                ->with('error', 'حدث خطأ أثناء إضافة أذن التسليم: ' . $e->getMessage())
                ->withInput();
        }
    }

    /**
     * Show the specified resource.
     */
    public function show($id)
    {
        $deliveryNote = DeliveryNote::with([
            'material',
            'receiver',
            'recordedBy',
            'approvedBy',
            'supplier',
            'destination'
        ])->findOrFail($id);

        // Load operation logs
        $operationLogs = $deliveryNote->operationLogs()->orderBy('created_at', 'desc')->get();

        return view('manufacturing::warehouses.delivery-notes.show', compact('deliveryNote', 'operationLogs'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $deliveryNote = DeliveryNote::findOrFail($id);
        $materials = Material::all();
        $suppliers = Supplier::all();
        $warehouses = Warehouse::all();
        $users = User::all();

        // ✅ استخدام المنتجات الموجودة في المستودع (اختياري الآن)
        $materialDetails = \App\Models\MaterialDetail::with(['material', 'warehouse', 'unit'])
            ->where('quantity', '>', 0)
            ->get();

        // Debug: Log the material details to see what we're getting
        \Illuminate\Support\Facades\Log::info('Edit Material Details Count: ' . $materialDetails->count());
        if ($materialDetails->count() > 0) {
            \Illuminate\Support\Facades\Log::info('Edit First Material Detail: ' . json_encode($materialDetails->first()));
        }

        return view('manufacturing::warehouses.delivery-notes.edit', compact(
            'deliveryNote',
            'materials',
            'suppliers',
            'warehouses',
            'users',
            'materialDetails'
        ));
    }

    /**
     * Update the specified resource in storage.
     * ✅ تم التعديل: دعم تحديث الأذن بدون مادة
     */
    public function update(Request $request, $id)
    {
        try {
            $deliveryNote = DeliveryNote::findOrFail($id);
            $oldValues = $deliveryNote->toArray();
            $type = $deliveryNote->type;

            // ✅ تحديث التحقق: material_id اختياري، warehouse_id إجباري
            $validated = $request->validate([
                'delivery_number' => 'required|string|unique:delivery_notes,note_number,' . $deliveryNote->id,
                'delivery_date' => 'required|date',
                'material_id' => 'nullable|exists:materials,id', // ✅ اختياري
                'material_detail_id' => 'nullable|exists:material_details,id', // ✅ اختياري
                'warehouse_id' => 'required|exists:warehouses,id', // ✅ إجباري
                'actual_weight' => 'required|numeric|min:0|gt:0',
                'weight_from_scale' => 'required|numeric|min:0', // ✅ مطلوب
                'invoice_weight' => 'nullable|numeric|min:0',
                'driver_name' => 'nullable|string|max:255',
                'vehicle_number' => 'nullable|string|max:50',
                'received_by' => 'nullable|exists:users,id',
                'supplier_id' => $type === 'incoming' ? 'required|exists:suppliers,id' : 'nullable',
                'destination_id' => $type === 'outgoing' ? 'required|string' : 'nullable', // ✅ قبول أي قيمة نصية
                'invoice_number' => 'nullable|string|max:100',
                'invoice_reference_number' => 'nullable|string|max:100',
                'notes' => 'nullable|string',
            ], [
                // رسائل الخطأ بالعربي
                'delivery_number.required' => 'رقم الأذن مطلوب',
                'delivery_number.string' => 'رقم الأذن يجب أن يكون نصاً',
                'delivery_number.unique' => 'رقم الأذن موجود بالفعل',
                'delivery_date.required' => 'التاريخ مطلوب',
                'delivery_date.date' => 'التاريخ غير صحيح',
                'warehouse_id.required' => 'المستودع مطلوب',
                'warehouse_id.exists' => 'المستودع المختار غير موجود',
                'material_id.exists' => 'المادة المختارة غير موجودة',
                'material_detail_id.exists' => 'تفاصيل المادة غير موجودة',

                'actual_weight.numeric' => 'الوزن يجب أن يكون رقماً',
                'actual_weight.gt' => 'الوزن يجب أن يكون أكبر من صفر',
                'weight_from_scale.required' => 'الوزن من الميزان مطلوب',
                'weight_from_scale.numeric' => 'وزن الميزان يجب أن يكون رقماً',
                'weight_from_scale.min' => 'وزن الميزان لا يمكن أن يكون سالباً',
                'invoice_weight.numeric' => 'وزن الفاتورة يجب أن يكون رقماً',
                'driver_name.string' => 'اسم السائق يجب أن يكون نصاً',
                'driver_name.max' => 'اسم السائق طويل جداً',
                'vehicle_number.string' => 'رقم المركبة يجب أن يكون نصاً',
                'vehicle_number.max' => 'رقم المركبة طويل جداً',
                'received_by.exists' => 'المستخدم المختار غير موجود',
                'supplier_id.required' => 'المورد مطلوب للأذن الواردة',
                'supplier_id.exists' => 'المورد المختار غير موجود',
                'destination_id.required' => 'الوجهة مطلوبة للأذن الصادرة',
                'destination_id.string' => 'الوجهة يجب أن تكون نصاً',
                'invoice_number.string' => 'رقم الفاتورة يجب أن يكون نصاً',
                'invoice_reference_number.string' => 'رقم مرجع الفاتورة يجب أن يكون نصاً',
                'notes.string' => 'الملاحظات يجب أن تكون نصاً',
            ]);

            // Prepare the data
            $validated['note_number'] = $validated['delivery_number'];
            unset($validated['delivery_number']);

            // Calculate weight discrepancy
            if ($validated['actual_weight'] && isset($validated['invoice_weight']) && $validated['invoice_weight']) {
                $validated['weight_discrepancy'] = $validated['actual_weight'] - $validated['invoice_weight'];
            }

            // Map delivered_weight to actual_weight for backward compatibility
            $validated['delivered_weight'] = $validated['actual_weight'];

            // Update the delivery note
            $deliveryNote->update($validated);
            $newValues = $deliveryNote->fresh()->toArray();

            // Check for weight discrepancy and notify
            $weightDiscrepancy = $validated['weight_discrepancy'] ?? null;
            if ($weightDiscrepancy && abs($weightDiscrepancy) > 0) {
                try {
                    $users = User::where('id', '!=', Auth::id())->get();
                    foreach ($users as $user) {
                        $this->notificationService->notifyWeightDiscrepancy(
                            $user,
                            $deliveryNote->fresh(),
                            abs($weightDiscrepancy),
                            Auth::user()
                        );
                    }

                    // ✅ تخزين إشعار اختلاف الوزن في قاعدة البيانات
                    $this->storeNotification(
                        'weight_discrepancy_detected',
                        'اختلاف في الوزن',
                        'تم اكتشاف اختلاف في الوزن لأذن التسليم رقم ' . $deliveryNote->note_number . ' (الفرق: ' . abs($weightDiscrepancy) . ' كجم)',
                        'warning',
                        'fas fa-exclamation-triangle',
                        route('manufacturing.delivery-notes.show', $deliveryNote->id)
                    );
                } catch (\Exception $notifError) {
                    Log::warning('Failed to send weight discrepancy notifications: ' . $notifError->getMessage());
                }
            }

            // Log the operation
            try {
                $this->logOperation(
                    'update',
                    'Update Delivery Note',
                    'تم تحديث أذن تسليم: ' . $deliveryNote->note_number,
                    'delivery_notes',
                    $deliveryNote->id,
                    $oldValues,
                    $newValues
                );
            } catch (\Exception $logError) {
                Log::error('Failed to log delivery note update: ' . $logError->getMessage());
                // Don't throw - just log the error
            }

            // إرسال إشعار بالتحديث
            try {
                $users = User::where('id', '!=', Auth::id())->get();
                foreach ($users as $user) {
                    $this->notificationService->notifyDeliveryNoteRegistered(
                        $user,
                        $deliveryNote->fresh(),
                        Auth::user()
                    );
                }

                // ✅ تخزين إشعار التحديث في قاعدة البيانات
                $this->storeNotification(
                    'delivery_note_updated',
                    'تحديث أذن تسليم',
                    'تم تحديث أذن التسليم برقم: ' . $deliveryNote->note_number,
                    'warning',
                    'fas fa-edit',
                    route('manufacturing.delivery-notes.show', $deliveryNote->id)
                );
            } catch (\Exception $notifError) {
                Log::warning('Failed to send update notifications: ' . $notifError->getMessage());
            }

            return redirect()->route('manufacturing.delivery-notes.index')
                ->with('success', 'تم تحديث أذن التسليم بنجاح');
        } catch (\Exception $e) {
            Log::error('Error updating delivery note: ' . $e->getMessage(), [
                'exception' => $e,
                'delivery_note_id' => $id,
                'input' => $request->all()
            ]);
            return redirect()->back()
                ->with('error', 'حدث خطأ أثناء تحديث أذن التسليم: ' . $e->getMessage())
                ->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        try {
            $deliveryNote = DeliveryNote::findOrFail($id);
            $oldValues = $deliveryNote->toArray();

            // Log the operation before deletion
            try {
                $this->logOperation(
                    'delete',
                    'Delete Delivery Note',
                    'تم حذف أذن تسليم: ' . $deliveryNote->note_number,
                    'delivery_notes',
                    $deliveryNote->id,
                    $oldValues,
                    null
                );
            } catch (\Exception $logError) {
                Log::error('Failed to log delivery note deletion: ' . $logError->getMessage());
                // Don't throw - just log the error
            }

            $deliveryNote->delete();

            // إرسال إشعار بحذف أذن التسليم
            try {
                $managers = User::where('role', 'admin')->orWhere('role', 'manager')->get();
                foreach ($managers as $manager) {
                    $this->notificationService->notifyCustom(
                        $manager,
                        'تم حذف أذن تسليم',
                        'تم حذف أذن التسليم برقم: ' . $deliveryNote->note_number,
                        'delete_delivery_note',
                        'danger',
                        'feather icon-trash-2',
                        route('manufacturing.delivery-notes.index')
                    );
                }

                // ✅ تخزين إشعار الحذف في قاعدة البيانات
                $this->storeNotification(
                    'delivery_note_deleted',
                    'حذف أذن تسليم',
                    'تم حذف أذن التسليم برقم: ' . $deliveryNote->note_number,
                    'danger',
                    'fas fa-trash',
                    route('manufacturing.delivery-notes.index')
                );
            } catch (\Exception $notifError) {
                Log::warning('Failed to send delivery note delete notifications: ' . $notifError->getMessage());
            }

            return redirect()->route('manufacturing.delivery-notes.index')
                ->with('success', 'تم حذف أذن التسليم بنجاح');
        } catch (\Exception $e) {
            Log::error('Error deleting delivery note: ' . $e->getMessage());
            return redirect()->back()
                ->with('error', 'حدث خطأ أثناء حذف أذن التسليم: ' . $e->getMessage());
        }
    }

    /**
     * Toggle delivery note status (active/inactive).
     */
    public function toggleStatus(Request $request, $id)
    {
        try {
            $deliveryNote = DeliveryNote::findOrFail($id);

            $oldStatus = $deliveryNote->is_active;
            $newStatus = !$oldStatus;

            $deliveryNote->update(['is_active' => $newStatus]);

            // Log the status change
            try {
                $this->logOperation(
                    'update',
                    'Toggle Status',
                    'تم تغيير حالة أذن التسليم من ' . ($oldStatus ? 'مفعلة' : 'معطلة') . ' إلى ' . ($newStatus ? 'مفعلة' : 'معطلة'),
                    'delivery_notes',
                    $deliveryNote->id,
                    ['is_active' => $oldStatus],
                    ['is_active' => $newStatus]
                );
            } catch (\Exception $logError) {
                Log::error('Failed to log delivery note status change: ' . $logError->getMessage());
                // Don't throw - just log the error
            }

            $statusText = $newStatus ? 'مفعلة' : 'معطلة';

            // إرسال إشعار بتغيير حالة أذن التسليم
            try {
                $managers = User::where('role', 'admin')->orWhere('role', 'manager')->get();
                foreach ($managers as $manager) {
                    $this->notificationService->notifyCustom(
                        $manager,
                        'تغيير حالة أذن التسليم',
                        'تم تغيير حالة أذن التسليم رقم ' . $deliveryNote->note_number . ' إلى ' . $statusText,
                        'toggle_delivery_note_status',
                        'info',
                        'feather icon-toggle-' . ($newStatus ? 'right' : 'left'),
                        route('manufacturing.delivery-notes.show', $deliveryNote->id)
                    );
                }

                // ✅ تخزين إشعار تغيير الحالة في قاعدة البيانات
                $this->storeNotification(
                    'delivery_note_status_changed',
                    'تغيير حالة أذن التسليم',
                    'تم تغيير حالة أذن التسليم رقم ' . $deliveryNote->note_number . ' إلى ' . $statusText,
                    'info',
                    'fas fa-exchange-alt',
                    route('manufacturing.delivery-notes.show', $deliveryNote->id)
                );
            } catch (\Exception $notifError) {
                Log::warning('Failed to send delivery note status toggle notifications: ' . $notifError->getMessage());
            }

            return redirect()->back()
                           ->with('success', 'تم تغيير حالة أذن التسليم بنجاح');
        } catch (\Exception $e) {
            Log::error('Error toggling delivery note status: ' . $e->getMessage());
            return redirect()->back()
                           ->withErrors(['error' => 'فشل في تغيير حالة أذن التسليم: ' . $e->getMessage()]);
        }
    }

    /**
     * Add invoice details to an existing delivery note
     */
    public function addInvoiceDetails(Request $request, $id)
    {
        try {
            $deliveryNote = DeliveryNote::findOrFail($id);
            $oldValues = $deliveryNote->toArray();

            $validated = $request->validate([
                'invoice_number' => 'required|string|max:100',
                'invoice_weight' => 'required|numeric|min:0',
                'invoice_reference_number' => 'nullable|string|max:100',
            ]);

            $validated['approved_by'] = Auth::id();
            $validated['approved_at'] = now();

            // Calculate discrepancy
            if ($deliveryNote->actual_weight) {
                $validated['weight_discrepancy'] = $deliveryNote->actual_weight - $validated['invoice_weight'];
            }

            $deliveryNote->update($validated);
            $newValues = $deliveryNote->fresh()->toArray();

            // Log the operation
            try {
                $this->logOperation(
                    'update',
                    'Add Invoice Details',
                    'تم إضافة تفاصيل الفاتورة لأذن التسليم: ' . $deliveryNote->note_number,
                    'delivery_notes',
                    $deliveryNote->id,
                    $oldValues,
                    $newValues
                );
            } catch (\Exception $logError) {
                Log::error('Failed to log invoice details addition: ' . $logError->getMessage());
                // Don't throw
            }

            // إرسال إشعار بإضافة تفاصيل الفاتورة
            try {
                $managers = User::where('role', 'admin')->orWhere('role', 'manager')->get();
                foreach ($managers as $manager) {
                    $this->notificationService->notifyCustom(
                        $manager,
                        'إضافة تفاصيل فاتورة',
                        'تم إضافة تفاصيل الفاتورة لأذن التسليم رقم: ' . $deliveryNote->note_number,
                        'add_invoice_details',
                        'success',
                        'feather icon-file-text',
                        route('manufacturing.delivery-notes.show', $deliveryNote->id)
                    );
                }

                // ✅ تخزين إشعار إضافة تفاصيل الفاتورة في قاعدة البيانات
                $this->storeNotification(
                    'invoice_details_added',
                    'إضافة تفاصيل فاتورة',
                    'تم إضافة تفاصيل الفاتورة لأذن التسليم رقم: ' . $deliveryNote->note_number . ' (فاتورة: ' . $validated['invoice_number'] . ')',
                    'success',
                    'fas fa-file-invoice',
                    route('manufacturing.delivery-notes.show', $deliveryNote->id)
                );
            } catch (\Exception $notifError) {
                Log::warning('Failed to send add invoice details notifications: ' . $notifError->getMessage());
            }

            return redirect()->back()
                ->with('success', 'تم إضافة تفاصيل الفاتورة بنجاح');
        } catch (\Exception $e) {
            Log::error('Error adding invoice details: ' . $e->getMessage());
            return redirect()->back()
                ->with('error', 'حدث خطأ: ' . $e->getMessage());
        }
    }

    /**
     * Update delivery note status (pending, approved, rejected, completed)
     */
    public function updateStatus(Request $request, $id)
    {
        try {
            $deliveryNote = DeliveryNote::findOrFail($id);
            $oldValues = $deliveryNote->toArray();

            $validated = $request->validate([
                'status' => 'required|in:pending,approved,rejected,completed',
            ]);

            $deliveryNote->update($validated);
            $newValues = $deliveryNote->fresh()->toArray();

            // Log the operation
            try {
                $statusLabel = \App\Models\DeliveryNoteStatus::from($validated['status'])->label();
                $this->logOperation(
                    'update',
                    'Update Status',
                    'تم تغيير حالة أذن التسليم إلى ' . $statusLabel . ': ' . $deliveryNote->note_number,
                    'delivery_notes',
                    $deliveryNote->id,
                    $oldValues,
                    $newValues
                );
            } catch (\Exception $logError) {
                Log::error('Failed to log delivery note status update: ' . $logError->getMessage());
                // Don't throw - just log the error
            }

            // إرسال إشعار بتحديث حالة أذن التسليم
            try {
                $statusLabel = \App\Models\DeliveryNoteStatus::from($validated['status'])->label();
                $managers = User::where('role', 'admin')->orWhere('role', 'manager')->get();
                foreach ($managers as $manager) {
                    $this->notificationService->notifyCustom(
                        $manager,
                        'تحديث حالة أذن التسليم',
                        'تم تغيير حالة أذن التسليم رقم ' . $deliveryNote->note_number . ' إلى ' . $statusLabel,
                        'update_delivery_note_status',
                        'info',
                        'feather icon-edit',
                        route('manufacturing.delivery-notes.show', $deliveryNote->id)
                    );
                }

                // ✅ تخزين إشعار تحديث الحالة في قاعدة البيانات
                $this->storeNotification(
                    'delivery_note_status_updated',
                    'تحديث حالة أذن التسليم',
                    'تم تغيير حالة أذن التسليم رقم ' . $deliveryNote->note_number . ' إلى ' . $statusLabel,
                    'info',
                    'fas fa-sync-alt',
                    route('manufacturing.delivery-notes.show', $deliveryNote->id)
                );
            } catch (\Exception $notifError) {
                Log::warning('Failed to send delivery note status update notifications: ' . $notifError->getMessage());
            }

            return redirect()->back()
                           ->with('success', 'تم تحديث حالة الأذن بنجاح');
        } catch (\Exception $e) {
            Log::error('Error updating delivery note status: ' . $e->getMessage());
            return redirect()->back()
                           ->withErrors(['error' => 'فشل في تحديث حالة الأذن: ' . $e->getMessage()]);
        }
    }

    /**
     * Change delivery note status (active/inactive)
     */
    public function changeStatus(Request $request, $id)
    {
        try {
            $deliveryNote = DeliveryNote::findOrFail($id);
            $oldValues = $deliveryNote->toArray();

            $validated = $request->validate([
                'is_active' => 'required|boolean',
            ]);

            $deliveryNote->update($validated);
            $newValues = $deliveryNote->fresh()->toArray();

            // Log the operation
            try {
                $statusText = $validated['is_active'] ? 'فعّالة' : 'معطّلة';
                $this->logOperation(
                    'update',
                    'Change Status',
                    'تم تغيير حالة أذن التسليم إلى ' . $statusText . ': ' . $deliveryNote->note_number,
                    'delivery_notes',
                    $deliveryNote->id,
                    $oldValues,
                    $newValues
                );
            } catch (\Exception $logError) {
                Log::error('Failed to log status change: ' . $logError->getMessage());
                // Don't throw
            }

            // إرسال إشعار بتغيير حالة أذن التسليم
            try {
                $statusText = $validated['is_active'] ? 'فعّالة' : 'معطّلة';
                $managers = User::where('role', 'admin')->orWhere('role', 'manager')->get();
                foreach ($managers as $manager) {
                    $this->notificationService->notifyCustom(
                        $manager,
                        'تغيير حالة أذن التسليم',
                        'تم تغيير حالة أذن التسليم رقم ' . $deliveryNote->note_number . ' إلى ' . $statusText,
                        'change_delivery_note_status',
                        'info',
                        'feather icon-toggle-' . ($validated['is_active'] ? 'right' : 'left'),
                        route('manufacturing.delivery-notes.show', $deliveryNote->id)
                    );
                }

                // ✅ تخزين إشعار تغيير الحالة النشطة في قاعدة البيانات
                $this->storeNotification(
                    'delivery_note_active_status_changed',
                    'تغيير حالة النشاط',
                    'تم تغيير حالة نشاط أذن التسليم رقم ' . $deliveryNote->note_number . ' إلى ' . $statusText,
                    $validated['is_active'] ? 'success' : 'warning',
                    $validated['is_active'] ? 'fas fa-check-circle' : 'fas fa-ban',
                    route('manufacturing.delivery-notes.show', $deliveryNote->id)
                );
            } catch (\Exception $notifError) {
                Log::warning('Failed to send delivery note status change notifications: ' . $notifError->getMessage());
            }

            return redirect()->back()
                ->with('success', 'تم تغيير حالة الأذن بنجاح');
        } catch (\Exception $e) {
            Log::error('Error changing delivery note status: ' . $e->getMessage());
            return redirect()->back()
                ->with('error', 'حدث خطأ: ' . $e->getMessage());
        }
    }
}
