<?php

namespace Modules\Manufacturing\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use App\Models\DeliveryNote;
use App\Models\Material;
use App\Models\Supplier;
use App\Models\Warehouse;
use App\Models\User;
use Modules\Manufacturing\Traits\LogsOperations;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Auth;

class DeliveryNoteController extends Controller
{
    use LogsOperations;

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $deliveryNotes = DeliveryNote::with(['material', 'receiver', 'supplier', 'destination'])->get();
        return view('manufacturing::warehouses.delivery-notes.index', compact('deliveryNotes'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        // استخدام المنتجات الموجودة في المستودع بدلاً من تكرارها
        $materialDetails = \App\Models\MaterialDetail::with(['material', 'warehouse', 'unit'])
            ->where('quantity', '>', 0)
            ->get();

        $suppliers = Supplier::all();
        $warehouses = Warehouse::all();
        $users = User::all();

        // توليد رقم الأذن تلقائياً
        $autoGeneratedNumber = $this->generateDeliveryNoteNumber();

        return view('manufacturing::warehouses.delivery-notes.create', compact(
            'materialDetails',
            'suppliers',
            'warehouses',
            'users',
            'autoGeneratedNumber'
        ));
    }

    /**
     * Generate a unique delivery note number
     */
    private function generateDeliveryNoteNumber()
    {
        $prefix = 'DN-' . date('Y') . '-';
        $lastNote = DeliveryNote::where('note_number', 'like', $prefix . '%')
            ->orderBy('note_number', 'desc')
            ->first();

        if ($lastNote) {
            // Extract the number from the last note
            $lastNumber = (int) substr($lastNote->note_number, strlen($prefix));
            $newNumber = $lastNumber + 1;
        } else {
            $newNumber = 1;
        }

        return $prefix . str_pad($newNumber, 4, '0', STR_PAD_LEFT);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        try {
            // التحقق من البيانات بناءً على النوع
            $type = $request->input('type', 'incoming');

            // إذا كان الرقم فارغاً، توليد رقم جديد
            $deliveryNumber = $request->input('delivery_number');
            if (empty($deliveryNumber)) {
                $deliveryNumber = $this->generateDeliveryNoteNumber();
            }

            $validated = $request->validate([
                'type' => 'required|in:incoming,outgoing',
                'delivery_date' => 'required|date',
                'material_detail_id' => 'required|exists:material_details,id',
                'delivery_quantity' => 'required|numeric|min:0|gt:0',
                'actual_weight' => 'required|numeric|min:0|gt:0',
                'invoice_weight' => 'nullable|numeric|min:0',
                'driver_name' => 'nullable|string|max:255',
                'vehicle_number' => 'nullable|string|max:50',
                'received_by' => 'nullable|exists:users,id',
                'supplier_id' => $type === 'incoming' ? 'required|exists:suppliers,id' : 'nullable',
                'destination_id' => $type === 'outgoing' ? 'required|exists:warehouses,id' : 'nullable',
                'invoice_number' => 'nullable|string|max:100',
                'invoice_reference_number' => 'nullable|string|max:100',
                'notes' => 'nullable|string',
            ]);

            // جلب تفاصيل المادة من المستودع
            $materialDetail = \App\Models\MaterialDetail::findOrFail($validated['material_detail_id']);

            // Prepare the data
            $validated['note_number'] = $deliveryNumber;

            // استخدام البيانات الموجودة بالفعل بدلاً من تكرارها
            $validated['material_id'] = $materialDetail->material_id;
            $validated['delivered_weight'] = $validated['actual_weight'];

            // Set the user fields
            $validated['received_by'] = $validated['received_by'] ?? Auth::id() ?? 1;
            $validated['recorded_by'] = Auth::id() ?? 1;

            // Calculate weight discrepancy
            if ($validated['actual_weight'] && $validated['invoice_weight']) {
                $validated['weight_discrepancy'] = $validated['actual_weight'] - $validated['invoice_weight'];
            }

            // Create the delivery note
            $deliveryNote = DeliveryNote::create($validated);

            // تحديث كمية المستودع حسب نوع الأذن
            try {
                if ($type === 'incoming') {
                    // أذن واردة - زيادة الكمية
                    $materialDetail->addIncomingQuantity(
                        $validated['delivery_quantity'],  // الكمية المدخلة من الأذن
                        $validated['actual_weight'],
                        $validated['invoice_weight'] ?? $validated['actual_weight']
                    );
                } elseif ($type === 'outgoing') {
                    // أذن صادرة - تقليل الكمية
                    $materialDetail->reduceOutgoingQuantity($validated['delivery_quantity']);
                }
            } catch (\Exception $inventoryError) {
                Log::error('Failed to update inventory: ' . $inventoryError->getMessage());
                // Delete the delivery note if inventory update fails
                $deliveryNote->delete();
                throw new \Exception('فشل تحديث المستودع: ' . $inventoryError->getMessage());
            }

            // Log the operation
            try {
                $this->logOperation(
                    'create',
                    'Create Delivery Note',
                    'تم إنشاء أذن تسليم ' . ($type === 'incoming' ? 'واردة' : 'صادرة') . ' جديدة: ' . $deliveryNote->note_number,
                    'delivery_notes',
                    $deliveryNote->id,
                    null,
                    $deliveryNote->toArray()
                );
            } catch (\Exception $logError) {
                Log::error('Failed to log delivery note creation: ' . $logError->getMessage());
                // Don't throw - just log the error, operation already completed
            }

            return redirect()->route('manufacturing.delivery-notes.index')
                ->with('success', 'تم إضافة أذن التسليم بنجاح وتحديث كمية المستودع');
        } catch (\Exception $e) {
            Log::error('Error creating delivery note: ' . $e->getMessage(), [
                'exception' => $e,
                'input' => $request->all()
            ]);
            return redirect()->back()
                ->with('error', 'حدث خطأ أثناء إضافة أذن التسليم: ' . $e->getMessage())
                ->withInput();
        }
    }

    /**
     * Show the specified resource.
     */
    public function show($id)
    {
        $deliveryNote = DeliveryNote::with([
            'material',
            'receiver',
            'recordedBy',
            'approvedBy',
            'supplier',
            'destination'
        ])->findOrFail($id);

        // Load operation logs
        $operationLogs = $deliveryNote->operationLogs()->orderBy('created_at', 'desc')->get();

        return view('manufacturing::warehouses.delivery-notes.show', compact('deliveryNote', 'operationLogs'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $deliveryNote = DeliveryNote::findOrFail($id);
        $materials = Material::all();
        $suppliers = Supplier::all();
        $warehouses = Warehouse::all();
        $users = User::all();

        return view('manufacturing::warehouses.delivery-notes.edit', compact(
            'deliveryNote',
            'materials',
            'suppliers',
            'warehouses',
            'users'
        ));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, $id)
    {
        try {
            $deliveryNote = DeliveryNote::findOrFail($id);
            $oldValues = $deliveryNote->toArray();
            $type = $deliveryNote->type;

            // التحقق من البيانات
            $validated = $request->validate([
                'delivery_number' => 'required|string|unique:delivery_notes,note_number,' . $deliveryNote->id,
                'delivery_date' => 'required|date',
                'material_id' => 'required|exists:materials,id',
                'actual_weight' => 'required|numeric|min:0|gt:0',
                'invoice_weight' => 'nullable|numeric|min:0',
                'driver_name' => 'nullable|string|max:255',
                'vehicle_number' => 'nullable|string|max:50',
                'received_by' => 'nullable|exists:users,id',
                'supplier_id' => $type === 'incoming' ? 'required|exists:suppliers,id' : 'nullable',
                'destination_id' => $type === 'outgoing' ? 'required|exists:warehouses,id' : 'nullable',
                'invoice_number' => 'nullable|string|max:100',
                'invoice_reference_number' => 'nullable|string|max:100',
                'notes' => 'nullable|string',
            ]);

            // Prepare the data
            $validated['note_number'] = $validated['delivery_number'];
            unset($validated['delivery_number']);

            // Calculate weight discrepancy
            if ($validated['actual_weight'] && $validated['invoice_weight']) {
                $validated['weight_discrepancy'] = $validated['actual_weight'] - $validated['invoice_weight'];
            }

            // Map delivered_weight to actual_weight for backward compatibility
            $validated['delivered_weight'] = $validated['actual_weight'];

            // Update the delivery note
            $deliveryNote->update($validated);
            $newValues = $deliveryNote->fresh()->toArray();

            // Log the operation
            try {
                $this->logOperation(
                    'update',
                    'Update Delivery Note',
                    'تم تحديث أذن تسليم: ' . $deliveryNote->note_number,
                    'delivery_notes',
                    $deliveryNote->id,
                    $oldValues,
                    $newValues
                );
            } catch (\Exception $logError) {
                Log::error('Failed to log delivery note update: ' . $logError->getMessage());
                // Don't throw - just log the error
            }

            return redirect()->route('manufacturing.delivery-notes.index')
                ->with('success', 'تم تحديث أذن التسليم بنجاح');
        } catch (\Exception $e) {
            Log::error('Error updating delivery note: ' . $e->getMessage(), [
                'exception' => $e,
                'delivery_note_id' => $id,
                'input' => $request->all()
            ]);
            return redirect()->back()
                ->with('error', 'حدث خطأ أثناء تحديث أذن التسليم: ' . $e->getMessage())
                ->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        try {
            $deliveryNote = DeliveryNote::findOrFail($id);
            $oldValues = $deliveryNote->toArray();

            // Log the operation before deletion
            try {
                $this->logOperation(
                    'delete',
                    'Delete Delivery Note',
                    'تم حذف أذن تسليم: ' . $deliveryNote->note_number,
                    'delivery_notes',
                    $deliveryNote->id,
                    $oldValues,
                    null
                );
            } catch (\Exception $logError) {
                Log::error('Failed to log delivery note deletion: ' . $logError->getMessage());
                // Don't throw - just log the error
            }

            $deliveryNote->delete();

            return redirect()->route('manufacturing.delivery-notes.index')
                ->with('success', 'تم حذف أذن التسليم بنجاح');
        } catch (\Exception $e) {
            Log::error('Error deleting delivery note: ' . $e->getMessage());
            return redirect()->back()
                ->with('error', 'حدث خطأ أثناء حذف أذن التسليم: ' . $e->getMessage());
        }
    }

    /**
     * Toggle delivery note status (active/inactive).
     */
    public function toggleStatus(Request $request, $id)
    {
        try {
            $deliveryNote = DeliveryNote::findOrFail($id);

            $oldStatus = $deliveryNote->is_active;
            $newStatus = !$oldStatus;

            $deliveryNote->update(['is_active' => $newStatus]);

            // Log the status change
            try {
                $this->logOperation(
                    'update',
                    'Toggle Status',
                    'تم تغيير حالة أذن التسليم من ' . ($oldStatus ? 'مفعلة' : 'معطلة') . ' إلى ' . ($newStatus ? 'مفعلة' : 'معطلة'),
                    'delivery_notes',
                    $deliveryNote->id,
                    ['is_active' => $oldStatus],
                    ['is_active' => $newStatus]
                );
            } catch (\Exception $logError) {
                Log::error('Failed to log delivery note status change: ' . $logError->getMessage());
                // Don't throw - just log the error
            }

            return redirect()->back()
                           ->with('success', 'تم تغيير حالة أذن التسليم بنجاح');
        } catch (\Exception $e) {
            Log::error('Error toggling delivery note status: ' . $e->getMessage());
            return redirect()->back()
                           ->withErrors(['error' => 'فشل في تغيير حالة أذن التسليم: ' . $e->getMessage()]);
        }
    }

    /**
     * Add invoice details to an existing delivery note
     */
    public function addInvoiceDetails(Request $request, $id)
    {
        try {
            $deliveryNote = DeliveryNote::findOrFail($id);
            $oldValues = $deliveryNote->toArray();

            $validated = $request->validate([
                'invoice_number' => 'required|string|max:100',
                'invoice_weight' => 'required|numeric|min:0',
                'invoice_reference_number' => 'nullable|string|max:100',
            ]);

            $validated['approved_by'] = Auth::id();
            $validated['approved_at'] = now();

            // Calculate discrepancy
            if ($deliveryNote->actual_weight) {
                $validated['weight_discrepancy'] = $deliveryNote->actual_weight - $validated['invoice_weight'];
            }

            $deliveryNote->update($validated);
            $newValues = $deliveryNote->fresh()->toArray();

            // Log the operation
            try {
                $this->logOperation(
                    'update',
                    'Add Invoice Details',
                    'تم إضافة تفاصيل الفاتورة لأذن التسليم: ' . $deliveryNote->note_number,
                    'delivery_notes',
                    $deliveryNote->id,
                    $oldValues,
                    $newValues
                );
            } catch (\Exception $logError) {
                Log::error('Failed to log invoice details addition: ' . $logError->getMessage());
                // Don't throw
            }

            return redirect()->back()
                ->with('success', 'تم إضافة تفاصيل الفاتورة بنجاح');
        } catch (\Exception $e) {
            Log::error('Error adding invoice details: ' . $e->getMessage());
            return redirect()->back()
                ->with('error', 'حدث خطأ: ' . $e->getMessage());
        }
    }

    /**
     * Update delivery note status (pending, approved, rejected, completed)
     */
    public function updateStatus(Request $request, $id)
    {
        try {
            $deliveryNote = DeliveryNote::findOrFail($id);
            $oldValues = $deliveryNote->toArray();

            $validated = $request->validate([
                'status' => 'required|in:pending,approved,rejected,completed',
            ]);

            $deliveryNote->update($validated);
            $newValues = $deliveryNote->fresh()->toArray();

            // Log the operation
            try {
                $statusLabel = \App\Models\DeliveryNoteStatus::from($validated['status'])->label();
                $this->logOperation(
                    'update',
                    'Update Status',
                    'تم تغيير حالة أذن التسليم إلى ' . $statusLabel . ': ' . $deliveryNote->note_number,
                    'delivery_notes',
                    $deliveryNote->id,
                    $oldValues,
                    $newValues
                );
            } catch (\Exception $logError) {
                Log::error('Failed to log delivery note status update: ' . $logError->getMessage());
                // Don't throw - just log the error
            }

            return redirect()->back()
                           ->with('success', 'تم تحديث حالة الأذن بنجاح');
        } catch (\Exception $e) {
            Log::error('Error updating delivery note status: ' . $e->getMessage());
            return redirect()->back()
                           ->withErrors(['error' => 'فشل في تحديث حالة الأذن: ' . $e->getMessage()]);
        }
    }

    /**
     * Change delivery note status (active/inactive)
     */
    public function changeStatus(Request $request, $id)
    {
        try {
            $deliveryNote = DeliveryNote::findOrFail($id);
            $oldValues = $deliveryNote->toArray();

            $validated = $request->validate([
                'is_active' => 'required|boolean',
            ]);

            $deliveryNote->update($validated);
            $newValues = $deliveryNote->fresh()->toArray();

            // Log the operation
            try {
                $statusText = $validated['is_active'] ? 'فعّالة' : 'معطّلة';
                $this->logOperation(
                    'update',
                    'Change Status',
                    'تم تغيير حالة أذن التسليم إلى ' . $statusText . ': ' . $deliveryNote->note_number,
                    'delivery_notes',
                    $deliveryNote->id,
                    $oldValues,
                    $newValues
                );
            } catch (\Exception $logError) {
                Log::error('Failed to log status change: ' . $logError->getMessage());
                // Don't throw
            }

            return redirect()->back()
                ->with('success', 'تم تغيير حالة الأذن بنجاح');
        } catch (\Exception $e) {
            Log::error('Error changing delivery note status: ' . $e->getMessage());
            return redirect()->back()
                ->with('error', 'حدث خطأ: ' . $e->getMessage());
        }
    }
}
