<?php

namespace Modules\Manufacturing\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Unit;
use App\Models\User;
use Modules\Manufacturing\Traits\LogsOperations;
use App\Traits\StoresNotifications;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Auth;

class UnitController extends Controller
{
    use LogsOperations, StoresNotifications;
    /**
     * Display a listing of the units with filtering and search.
     */
    public function index(Request $request)
    {
        $query = Unit::with(['creator']);
        $locale = \Illuminate\Support\Facades\App::getLocale();

        // Search filter
        if ($request->filled('search')) {
            $search = $request->get('search');
            $query->where(function ($q) use ($search) {
                $q->where('unit_name', 'like', "%{$search}%")
                  ->orWhere('unit_name_en', 'like', "%{$search}%")
                  ->orWhere('unit_code', 'like', "%{$search}%")
                  ->orWhere('unit_symbol', 'like', "%{$search}%");
            });
        }

        // Filter by type
        if ($request->filled('unit_type')) {
            $query->where('unit_type', $request->get('unit_type'));
        }

        // Filter by status
        if ($request->filled('is_active')) {
            $query->where('is_active', $request->boolean('is_active'));
        }

        $units = $query->paginate(15);

        return view('manufacturing::warehouses.settings.units.index', compact('units', 'locale'));
    }

    /**
     * Show the form for creating a new unit.
     */
    public function create()
    {
        $unitTypes = [
            'weight' => 'الوزن',
            'quantity' => 'الكمية',
        ];
        $locale = \Illuminate\Support\Facades\App::getLocale();

        // توليد الرمز تلقائياً
        $autoGeneratedCode = $this->generateUnitCode();

        return view('manufacturing::warehouses.settings.units.create', compact('unitTypes', 'autoGeneratedCode', 'locale'));
    }

    /**
     * Generate a unique unit code
     */
    private function generateUnitCode()
    {
        $prefix = 'U-';
        $lastUnit = Unit::where('unit_code', 'like', $prefix . '%')
            ->orderBy('unit_code', 'desc')
            ->first();

        if ($lastUnit) {
            $lastNumber = (int) substr($lastUnit->unit_code, strlen($prefix));
            $newNumber = $lastNumber + 1;
        } else {
            $newNumber = 1;
        }

        return $prefix . str_pad($newNumber, 4, '0', STR_PAD_LEFT);
    }

    /**
     * Store a newly created unit in storage.
     */
    public function store(Request $request)
    {
        try {
            // إذا كان الحقل فارغ، يتم إنشاء الرمز تلقائياً
            $unitCode = $request->input('unit_code');
            if (empty($unitCode)) {
                $unitCode = $this->generateUnitCode();
            }

            $validated = $request->validate([
                'unit_code' => 'required|string|unique:units,unit_code',
                'unit_name' => 'required|string|min:2|max:255',
                'unit_name_en' => 'nullable|string|min:2|max:255',
                'unit_symbol' => 'required|string|max:10',
                'unit_type' => 'required|in:weight,length,volume,area,quantity,time,temperature,other',
                'conversion_factor' => 'nullable|numeric|min:0',
                'base_unit' => 'nullable|exists:units,id',
                'description' => 'nullable|string|max:500',
                'is_active' => 'nullable|boolean',
            ]);

            // تحديث الرمز المُنتج تلقائياً إن وجد
            $validated['unit_code'] = $unitCode;

            $validated['created_by'] = Auth::id() ?? 1;
            $validated['is_active'] = $request->boolean('is_active', true);

            $unit = Unit::create($validated);

            // ✅ تخزين الإشعار
            $this->storeNotification(
                'unit_created',
                'تم إنشاء وحدة جديدة',
                'تم إنشاء وحدة جديدة: ' . $unit->unit_name . ' (' . $unit->unit_symbol . ')',
                'success',
                'fas fa-cube',
                route('manufacturing.warehouse-settings.units.index')
            );

            // تسجيل العملية
            try {
                $this->logOperation(
                    'create',
                    'Create Unit',
                    'تم إنشاء وحدة جديدة: ' . $unit->unit_name,
                    'units',
                    $unit->id,
                    null,
                    $unit->toArray()
                );
            } catch (\Exception $logError) {
                Log::error('Failed to log unit creation: ' . $logError->getMessage());
            }

            return redirect()->route('manufacturing.warehouse-settings.units.index')
                           ->with('success', 'تم إضافة الوحدة بنجاح');
        } catch (\Exception $e) {
            Log::error('Error creating unit: ' . $e->getMessage(), [
                'exception' => $e,
                'input' => $request->all()
            ]);
            return redirect()->back()
                           ->withInput()
                           ->withErrors(['error' => 'فشل في حفظ الوحدة: ' . $e->getMessage()]);
        }
    }

    /**
     * Display the specified unit.
     */
    public function show($id)
    {
        $unit = Unit::with(['creator'])->findOrFail($id);
        $locale = \Illuminate\Support\Facades\App::getLocale();

        return view('manufacturing::warehouses.settings.units.show', compact('unit', 'locale'));
    }

    /**
     * Show the form for editing the specified unit.
     */
    public function edit($id)
    {
        $unit = Unit::findOrFail($id);
        $locale = \Illuminate\Support\Facades\App::getLocale();

        $unitTypes = [
            'weight' => 'الوزن',
            'length' => 'الطول',
            'volume' => 'الحجم',
            'area' => 'المساحة',
            'quantity' => 'الكمية',
            'time' => 'الوقت',
            'temperature' => 'درجة الحرارة',
            'other' => 'أخرى',
        ];

        $baseUnits = Unit::where('id', '!=', $id)->get();

        return view('manufacturing::warehouses.settings.units.edit', compact('unit', 'unitTypes', 'baseUnits', 'locale'));
    }

    /**
     * Update the specified unit in storage.
     */
    public function update(Request $request, $id)
    {
        try {
            $unit = Unit::findOrFail($id);
            $oldValues = $unit->toArray();

            $validated = $request->validate([
                'unit_code' => 'required|string|unique:units,unit_code,' . $id,
                'unit_name' => 'required|string|min:2|max:255',
                'unit_name_en' => 'nullable|string|min:2|max:255',
                'unit_symbol' => 'required|string|max:10',
                'unit_type' => 'required|in:weight,length,volume,area,quantity,time,temperature,other',
                'conversion_factor' => 'nullable|numeric|min:0',
                'base_unit' => 'nullable|exists:units,id',
                'description' => 'nullable|string|max:500',
                'is_active' => 'nullable|boolean',
            ]);

            $validated['is_active'] = $request->boolean('is_active', true);

            $unit->update($validated);
            $newValues = $unit->fresh()->toArray();

            // ✅ تخزين الإشعار
            $this->storeNotification(
                'unit_updated',
                'تم تحديث وحدة',
                'تم تحديث وحدة: ' . $unit->unit_name . ' (' . $unit->unit_symbol . ')',
                'warning',
                'fas fa-edit',
                route('manufacturing.warehouse-settings.units.index')
            );

            // تسجيل العملية
            try {
                $this->logOperation(
                    'update',
                    'Update Unit',
                    'تم تحديث وحدة: ' . $unit->unit_name,
                    'units',
                    $unit->id,
                    $oldValues,
                    $newValues
                );
            } catch (\Exception $logError) {
                Log::error('Failed to log unit update: ' . $logError->getMessage());
            }

            return redirect()->route('manufacturing.warehouse-settings.units.index')
                           ->with('success', 'تم تحديث الوحدة بنجاح');
        } catch (\Exception $e) {
            Log::error('Error updating unit: ' . $e->getMessage(), [
                'exception' => $e,
                'unit_id' => $id,
                'input' => $request->all()
            ]);
            return redirect()->back()
                           ->withInput()
                           ->withErrors(['error' => 'فشل في تحديث الوحدة: ' . $e->getMessage()]);
        }
    }

    /**
     * Remove the specified unit from storage.
     */
    public function destroy($id)
    {
        try {
            $unit = Unit::findOrFail($id);
            $oldValues = $unit->toArray();

            // Check if unit is used in materials
            if ($unit->materials()->count() > 0) {
                return redirect()->route('manufacturing.warehouse-settings.units.index')
                               ->with('error', 'لا يمكن حذف هذه الوحدة لأنها مستخدمة في مواد');
            }

            // ✅ تخزين الإشعار
            $this->storeNotification(
                'unit_deleted',
                'تم حذف وحدة',
                'تم حذف وحدة: ' . $unit->unit_name . ' (' . $unit->unit_symbol . ')',
                'danger',
                'fas fa-trash',
                route('manufacturing.warehouse-settings.units.index')
            );

            // تسجيل العملية قبل الحذف
            try {
                $this->logOperation(
                    'delete',
                    'Delete Unit',
                    'تم حذف وحدة: ' . $unit->unit_name,
                    'units',
                    $unit->id,
                    $oldValues,
                    null
                );
            } catch (\Exception $logError) {
                Log::error('Failed to log unit deletion: ' . $logError->getMessage());
            }

            $unit->delete();

            return redirect()->route('manufacturing.warehouse-settings.units.index')
                           ->with('success', 'تم حذف الوحدة بنجاح');
        } catch (\Exception $e) {
            Log::error('Error deleting unit: ' . $e->getMessage());
            return redirect()->back()
                           ->withErrors(['error' => 'فشل في حذف الوحدة: ' . $e->getMessage()]);
        }
    }

    /**
     * Bulk delete units.
     */
    public function bulkDelete(Request $request)
    {
        $ids = $request->input('ids', []);

        if (empty($ids)) {
            return redirect()->back()->with('error', 'الرجاء اختيار وحدة واحدة على الأقل');
        }

        Unit::whereIn('id', $ids)->delete();

        return redirect()->route('manufacturing.warehouse-settings.units.index')
                       ->with('success', 'تم حذف الوحدات المختارة بنجاح');
    }

    /**
     * Toggle unit status (active/inactive).
     */
    public function toggleStatus(Request $request, $id)
    {
        try {
            $unit = Unit::findOrFail($id);

            $oldStatus = $unit->is_active;
            $newStatus = !$oldStatus;

            $unit->update(['is_active' => $newStatus]);

            // ✅ تخزين الإشعار
            $this->storeNotification(
                'unit_status_changed',
                'تم تغيير حالة وحدة',
                'تم تغيير حالة الوحدة ' . $unit->unit_name . ' من ' . ($oldStatus ? 'مفعلة' : 'معطلة') . ' إلى ' . ($newStatus ? 'مفعلة' : 'معطلة'),
                'info',
                'fas fa-toggle-' . ($newStatus ? 'on' : 'off'),
                route('manufacturing.warehouse-settings.units.index')
            );

            // Log the status change
            try {
                $this->logOperation(
                    'update',
                    'Toggle Status',
                    'تم تغيير حالة الوحدة من ' . ($oldStatus ? 'مفعلة' : 'معطلة') . ' إلى ' . ($newStatus ? 'مفعلة' : 'معطلة'),
                    'units',
                    $unit->id,
                    ['is_active' => $oldStatus],
                    ['is_active' => $newStatus]
                );
            } catch (\Exception $logError) {
                Log::error('Failed to log unit status change: ' . $logError->getMessage());
            }

            return redirect()->back()
                           ->with('success', 'تم تغيير حالة الوحدة بنجاح');
        } catch (\Exception $e) {
            Log::error('Error toggling unit status: ' . $e->getMessage());
            return redirect()->back()
                           ->withErrors(['error' => 'فشل في تغيير حالة الوحدة: ' . $e->getMessage()]);
        }
    }
}
